spring:
  datasource:
    url: jdbc:h2:mem:motorsports;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /open-api
  swagger-ui:
    path: /