openapi: "3.0.3"
info:
  title: Motorsports Manager
  version: 1.0.0
  description: The ultimate gaming experience
  contact:
    name: SDET
    email: sdet@praegus.nl
paths:
  /api/chassis:
    get:
      summary: get all chassis
      operationId: getChassis
      tags:
        - chassis
      responses:
        200:
          description: chassis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChassisResponse'

components:
  schemas:
    ChassisResponse:
      type: object
      properties:
        name:
          type: string
        color:
          type: string