openapi: 3.0.3
info:
  title: Motorsports Manager
  version: 1.0.0
  description: The ultimate gaming experience
  contact:
    name: SDET
    email: sdet@praegus.nl
servers:
  - url: http://localhost:8080
paths:
  /chassis:
    get:
      summary: Get all chassis
      operationId: getChassis
      tags:
        - chassis
      responses:
        200:
          description: chassis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChassisResponse'
  /profiles:
    get:
      summary: Get all profiles
      operationId: getAllProfiles
      tags:
        - profile
      responses:
        200:
          description: Retrieve all profiles
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ProfileResponse'
        404:
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new profile
      operationId: createProfile
      tags:
        - profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileRequest'
      responses:
        201:
          description: New profile created
          headers:
            location:
              schema:
                type: string
              description: Location of the created profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        409:
          description: Profile already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profiles/{name}:
    get:
      summary: Retrieve a profile by name
      operationId: getProfileByName
      tags:
        - profile
      parameters:
        - name: name
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ProfileName'
      responses:
        200:
          description: Response profile object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'

  /organizations:
    get:
      summary: Get all organizations
      operationId: getAllOrganizations
      tags:
        - organization
      responses:
        200:
          description: Retrieve all organizations
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/OrganizationResponse'

    post:
      summary: Create a new organization
      operationId: createOrganization
      tags:
        - organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
      responses:
        201:
          description: New organization created
          headers:
            location:
              schema:
                type: string
              description: Location of the created organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
        409:
          description: Organization already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /organizations/{name}:
    get:
      summary: Retrieve an organization by name
      operationId: getOrganizationByName
      tags:
        - organization
      parameters:
        - name: name
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/OrganizationName'
      responses:
        200:
          description: Response organization object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
components:
  schemas:
    ChassisResponse:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
    ProfileRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ProfileName'
          nullable: false
    ProfileResponse:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ProfileName'
    ProfileName:
      description: 'Name of the profile to create'
      type: string
      pattern: '^[a-zA-Z0-9]*$'
      example: 'MyProfile'
      minLength: 1
      maxLength: 10
    OrganizationRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/OrganizationName'
          nullable: false
    OrganizationResponse:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/OrganizationName'
    OrganizationName:
      description: 'Name of the organization to create'
      type: string
      pattern: '^[a-zA-Z0-9]*$'
      example: 'MyOrg'
      minLength: 1
      maxLength: 20
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
          description: a URI identifier that categorizes the error
        title:
          type: string
          description: a brief, human-readable message about the error
        status:
          type: int
          description: the HTTP response code (optional)
        detail:
          type: string
          description: a human-readable explanation of the error
        instance:
          type: string
          description: a URI that identifies the specific occurrence of the error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
    FieldError:
      type: object
      properties:
        field:
          type: string
          description: the field that the error is thrown on
        error:
          type: string
          description: the error message