openapi: 3.0.3
info:
  title: Motorsports Manager
  version: 1.0.0
  description: The ultimate gaming experience
  contact:
    name: SDET
    email: sdet@praegus.nl
servers:
  - url: http://localhost:8080
paths:
  /profile/{name}:
    get:
      summary: Retrieve a profile by name
      operationId: getProfileByName
      tags:
        - profile
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            example: 'MyProfile'
      responses:
        200:
          description:  Response profile object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
  /chassis:
    get:
      summary: Get all chassis
      operationId: getChassis
      tags:
        - chassis
      responses:
        200:
          description: chassis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChassisResponse'
  /profile:
    get:
      summary: Get all profiles
      operationId: getAllProfiles
      tags:
        - profile
      responses:
        200:
          description: Retrieve all profiles
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ProfileResponse'
        404:
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new profile
      operationId: createProfile
      tags:
        - profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileRequest'
      responses:
        201:
          description: New profile created
          headers:
            location:
              schema:
                type: string
              description: Location of the created profile
        409:
          description: Profile already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ChassisResponse:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
    ProfileRequest:
      type: object
      properties:
        name:
          description: 'Name of the profile to create'
          type: string
          pattern: '^[a-zA-Z0-9]{1,10}$'
          example: 'MyProfile'
          nullable: false
    ProfileResponse:
      type: object
      properties:
        name:
          type: string
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
          description: a URI identifier that categorizes the error
        title:
          type: string
          description: a brief, human-readable message about the error
        status:
          type: int
          description: the HTTP response code (optional)
        detail:
          type: string
          description: a human-readable explanation of the error
        instance:
          type: string
          description: a URI that identifies the specific occurrence of the error