openapi: "3.0.3"
info:
  title: Motorsports Manager
  version: 1.0.0
  description: The ultimate gaming experience
  contact:
    name: SDET
    email: sdet@praegus.nl
servers:
  - url: http://localhost:8080
paths:
  /chassis:
    get:
      summary: Get all chassis
      operationId: getChassis
      tags:
        - chassis
      responses:
        200:
          description: chassis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChassisResponse'
  /profile:
    get:
      summary: Get a profile
      operationId: getProfile
      tags:
        - profile
      responses:
        200:
          description: Retrieve a profile
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ProfileResponse'
    post:
      summary: Create a new profile
      operationId: createProfile
      tags:
        - profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileRequest'
      responses:
        201:
          description: OK

components:
  schemas:
    ChassisResponse:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
    ProfileRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 10
          minLength: 1
          pattern: '^[a-zA-Z0-9]+'
    ProfileResponse:
      type: object
      properties:
        name:
          type: string
