openapi: "3.0.3"
info:
  title: Motorsports Manager
  version: 1.0.0
  description: The ultimate gaming experience
  contact:
    name: SDET
    email: sdet@praegus.nl
servers:
  - url: http://localhost:8080
paths:
  /chassis:
    get:
      summary: get all chassis
      operationId: getChassis
      tags:
        - chassis
      responses:
        200:
          description: chassis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChassisResponse'
  /teams:
    get:
      summary: get all teams
      operationId: getTeams
      tags:
        - teams
      responses:
        200:
          description: retrieve teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamResponse'
    post:
      summary: create a new team
      operationId: createTeam
      tags:
        - teams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamRequest'
      responses:
        201:
          description: OK


components:
  schemas:
    ChassisResponse:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
    TeamRequest:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string
    TeamResponse:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string