spring:
  datasource:
    url: jdbc:h2:mem:motorsports;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
    path: /
    url: /specs.yml
server:
  error:
    include-binding-errors: always