name: Run Renovate Bot
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  RENOVATE_PLATFORM: 'github'
  RENOVATE_REPOSITORIES: 'praegus/MotorSportsManager'

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.5
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'info'
